# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: sling

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/flarco/dbio' go.mod
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/sling
    
    env:
      - CGO_ENABLED=1

    goarch:
      - amd64
      - arm64
    goos:
      # - linux
      # - windows
      - darwin
    ldflags:
      - "-X 'github.com/slingdata-io/sling-cli/core.Version={{.Version}}' -X 'github.com/slingdata-io/sling-cli/core/env.RudderstackKey={{.Env.RUDDERSTACK_KEY}}'"

universal_binaries:
  - id: sling
    replace: false

snapshot:
  name_template: "{{ incpatch .Version }}"

checksum:
  name_template: '{{ .Runtime.Goos }}.{{ .Runtime.Goarch }}.checksums.txt'

# mc policy set public DO/ocral/slingdata.io/cli
blobs:
  - provider: s3
    endpoint: https://nyc3.digitaloceanspaces.com
    bucket: ocral
    folder: "slingdata.io/dist/{{.Version}}"
    region: nyc3

release:
  mode: replace
  header: |
    ## Sling {{ .Tag }} ({{ .Date }})

brews:
  - name: sling
    repository:
      owner: slingdata-io
      name: homebrew-sling
      branch: main

    homepage: https:/slingdata.io/
    description: "Data Integration made simple, from the command line. Extract and load data from popular data sources to destinations with high performance and ease."