# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: sling

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/slingdata-io/sling' go.mod
    - go mod edit -droprequire='github.com/slingdata-io/sling' go.mod
    - go mod tidy

builds:
  - main: ./cmd/sling
    
    env:
      - CGO_ENABLED=1
    
    tags:
      - fts5

    goarch:
      - amd64
      - arm64
    
    goos:
      - darwin
    
    ldflags:
      - "-X 'github.com/slingdata-io/sling-cli/core.Version={{.Version}}' -X 'github.com/slingdata-io/sling-cli/core/env.PlausibleURL={{.Env.PLAUSIBLE_URL}}' -X 'github.com/slingdata-io/sling-cli/core/env.SentryDsn={{.Env.SENTRY_DSN}}'"

universal_binaries:
  - id: sling
    replace: false

snapshot:
  name_template: "{{ incpatch .Version }}"

checksum:
  name_template: '{{ .Runtime.Goos }}.{{ .Runtime.Goarch }}.checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

release:
  mode: replace
  header: |
    ## Sling {{ .Tag }} ({{ .Date }})

brews:
  - name: sling
    repository:
      owner: slingdata-io
      name: homebrew-sling
      branch: main

    homepage: https://slingdata.io/
    description: "Data Integration made simple, from the command line. Extract and load data from popular data sources to destinations with high performance and ease."