# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: sling

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/slingdata-io/sling' go.mod
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/sling
    
    env:
      - CGO_ENABLED=1
    
    tags:
      - fts5

    goarch:
      - amd64
      # - '386'
      # - arm64
      # - arm
    # goarm:
    #   - '6'
    #   - '7'
    goos:
      - linux
    ldflags:
      - "-X 'github.com/slingdata-io/sling-cli/core.Version={{.Version}}' -X 'github.com/slingdata-io/sling-cli/core/env.PlausibleURL={{.Env.PLAUSIBLE_URL}}' -X 'github.com/slingdata-io/sling-cli/core/env.SentryDsn={{.Env.SENTRY_DSN}}'"

snapshot:
  name_template: "{{ incpatch .Version }}"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

checksum:
  name_template: '{{ .Runtime.Goos }}.{{ .Runtime.Goarch }}.checksums.txt'

dockers:
  - dockerfile: 'cmd/sling/Dockerfile'
    image_templates:
    - "slingdata/sling:{{ .Tag }}"
    - "slingdata/sling:{{ .Tag }}-amd64"
    - "slingdata/sling:latest-amd64"
    - "slingdata/sling:latest"

# https://goreleaser.com/cookbooks/multi-platform-docker-images/#creating-multi-platform-docker-images-with-goreleaser
# docker_manifests:
# - name_template: 'slingdata/sling:latest'
#   image_templates:
#   - 'slingdata/sling:{{ .Tag }}-amd64'
#   - 'slingdata/sling:{{ .Tag }}-arm64'

# - name_template: 'slingdata/sling:{{ .Tag }}'
#   image_templates:
#   - 'slingdata/sling:{{ .Tag }}-amd64'
#   - 'slingdata/sling:{{ .Tag }}-arm64'

# mc policy set public DO/ocral/slingdata.io/cli
blobs:
  - provider: s3
    endpoint: https://nyc3.digitaloceanspaces.com
    bucket: ocral
    folder: "slingdata.io/dist/{{.Version}}"
    region: nyc3

release:
  mode: replace
  header: |
    ## Sling {{ .Tag }} ({{ .Date }})